# Generated by Django 4.2.8 on 2023-12-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, help_text='Не более 200 символов', max_length=200),
        ),
    ]
