# Generated by Django 4.2.8 on 2023-12-20 19:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_likes_post_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='не более 5000 символов', max_length=5000, null=True),
        ),
    ]
