# Generated by Django 4.2.8 on 2023-12-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
